"""update content models

Revision ID: 9190b25a36dd
Revises: 7836647eb4a7
Create Date: 2026-09-06 12:23:48.996348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9190b25a36dd'
down_revision: Union[str, Sequence[str], None] = '7836647eb4a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'category', name='uq_show_category')
    )
    op.create_index(op.f('ix_show_categories_id'), 'show_categories', ['id'], unique=False)
    op.create_unique_constraint('uq_episode_artwork_type', 'artwork', ['episode_id', 'artwork_type'])
    op.add_column('episodes', sa.Column('seed_episode_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_episodes_seed_episode_id'), 'episodes', ['seed_episode_id'], unique=True)
    op.alter_column(
    'publish_runs',
    'published_at',
    existing_type=sa.VARCHAR(length=50),
    type_=sa.DateTime(timezone=True),
    existing_nullable=False,
    postgresql_using="published_at::timestamp with time zone",
    )
    op.alter_column('publish_runs', 'shows_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('publish_runs', 'episodes_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_show_season_number', 'seasons', ['show_id', 'season_number'])
    op.add_column('shows', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_shows_slug'), 'shows', ['slug'], unique=True)
    op.drop_column('shows', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_shows_slug'), table_name='shows')
    op.drop_column('shows', 'slug')
    op.drop_constraint('uq_show_season_number', 'seasons', type_='unique')
    op.alter_column('publish_runs', 'episodes_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('publish_runs', 'shows_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('publish_runs', 'published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_episodes_seed_episode_id'), table_name='episodes')
    op.drop_column('episodes', 'seed_episode_id')
    op.drop_constraint('uq_episode_artwork_type', 'artwork', type_='unique')
    op.drop_index(op.f('ix_show_categories_id'), table_name='show_categories')
    op.drop_table('show_categories')
    # ### end Alembic commands ###
