"""add show artwork support

Revision ID: c50bf9b41cdc
Revises: df813e79ec88
Create Date: 2026-09-06 14:16:48.354786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50bf9b41cdc'
down_revision: Union[str, Sequence[str], None] = 'df813e79ec88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('show_id', sa.Integer(), nullable=True))
    op.alter_column('artwork', 'episode_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('uq_show_artwork_type', 'artwork', ['show_id', 'artwork_type'])
    op.create_foreign_key(None, 'artwork', 'shows', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artwork', type_='foreignkey')
    op.drop_constraint('uq_show_artwork_type', 'artwork', type_='unique')
    op.alter_column('artwork', 'episode_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('artwork', 'show_id')
    # ### end Alembic commands ###
