"""add validation issues

Revision ID: df813e79ec88
Revises: 9190b25a36dd
Create Date: 2026-09-06 12:37:04.174578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df813e79ec88'
down_revision: Union[str, Sequence[str], None] = '9190b25a36dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=30), nullable=False),
    sa.Column('entity', sa.String(length=30), nullable=False),
    sa.Column('seed_episode_id', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_issues_id'), 'validation_issues', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_issues_id'), table_name='validation_issues')
    op.drop_table('validation_issues')
    # ### end Alembic commands ###
